version: "3.8"

services:
  zian:
    container_name: zian
    hostname: zian.mm
    image: zian
    restart: always
    tty: true
    ports:
      - "80-88:80-88"
      - "443:443"
      - "5005:5005"
    volumes:
      - /home/nginx/:/home/nginx/
      - /home/webdav:/var/www/webdav
    working_dir: /home/nginx
    command: sh -c "nginx & goweb"

  transmission:
    container_name: transmission
    hostname: transmission.mm
    image: linuxserver/transmission
    tty: true
    ports:
      - "90:9091"
      - "51413:51413"
    volumes:
      - /home/nginx/transmission/:/downloads/

  quic:
    container_name: quic
    hostname: quic.mm
    image: nginx.quic
    restart: always
    tty: true
    ports:
      - "443:443"
    command: sh -c "nginx & bash"


  v2raya:
    container_name: v2raya
    hostname: v2raya.mm
    image: mzz2017/v2raya
    restart: always
    tty: true
    ports:
      - "2017:2017"
      - "10086:10086"
    environment:
      V2RAYA_V2RAY_BIN: /usr/local/bin/v2ray
    volumes:
      - /home/v2raya:/etc/v2raya
# 需指定V2RAYA_V2RAY_BIN才能使用多路
# https://www.freeclashnode.com/uploads/2024/12/0-20241221.txt
# 需在设置开启端口分享
# 分流模式RoutingA设置密码 inbound: httpauthin = http(address: 0.0.0.0, port: 10086, user: x, pass: x)
  webdav:
  # 文件配置备份系统
    container_name: webdav
    hostname: webdav
    image: webdav
    restart: always
    tty: true
    ports:
      - "5005:80"
    volumes:
      - /home/webdav:/var/www/html
    command: "nginx -g 'daemon off;'"

  mariadb:
    container_name: mariadb
    hostname: mariadb.mm
    image: mariadb10.11
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /home/mariadb/:/var/lib/mysql

  chronyd:
    container_name: chronyd
    hostname: chronyd.mm
    image: chronyd4.3
    restart: always
    tty: true
    ports:
      - "123:123/udp"
      - "323:323/udp"

  vlmcsd:
    container_name: vlmcsd
    hostname: vlmcsd.mm
    image: vlmcsd
    tty: true
    ports:
      - "1688:1688"

  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq.mm
    image: dnsmasq2.89
    tty: true
    volumes:
      - /etc/hosts:/etc/hosts
      - /logs/dnsmasq.log:/var/log/dnsmasq/dnsmasq.log
    ports:
      - "53:53/udp"

  dot:
    container_name: dot
    hostname: dot.mm
    image: dot
    tty: true
    ports:
      - "853:853/udp"
    command: "nginx -g 'daemon off;'"

  xunlei:
    container_name: xunlei
    hostname: xunlei.mm
    image: docker.io/cnk3x/xunlei
    user: root
    privileged: true
    tty: true
    volumes:
      - /home/nginx/xunlei/:/xunlei/downloads/
    environment:
      - XL_DASHBOARD_PORT=996
    ports:
      - "996:996"

  maomiav:
    container_name: maomiav
    hostname: maomiav.mm
    image: maomiav
    tty: true
#    ports:
#      - "213:213"

  socket5:
    container_name: socket5
    hostname: socket5.mm
    image: socket5
    tty: true
    ports:
      - "55555:55555"

  squid:
    container_name: squid5.7
    hostname: squid
    image: squid5.7
    tty: true
    ports:
      - "11111:3128"

  ollama:
    container_name: ollama
    hostname: ollama.service
    image: alpine/ollama
    tty: true
    ports:
      - "11434:11434"
    volumes:
      - /home/ollama/.ollama/:/root/.ollama/
    environment:
      - OLLAMA_KEEP_ALIVE=-1
  # ollama run qwen2.5-coder:0.5b

  test:
    container_name: test
    hostname: test.mm
    image: debian12.x
    tty: true
    tmpfs: /tmpfs/
    volumes:
      - /home/nginx/temp/:/temp/
    working_dir: /temp
    ports:
      - "2222:22"
# 默认进入temp目录操作: echo "cd /temp" >> .bashrc
