version: "3.8"

services:
  nginx:
    container_name: nginx
    hostname: nginx.mm
    image: nginx1.22
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - /home/nginx/:/home/nginx/
    working_dir: /home/nginx
    command: sh -c "nginx & /var/www/html/.go"
    #mkdir m3u8 note

  v2raya:
    container_name: v2raya
    hostname: v2raya.mm
    image: mzz2017/v2raya
    restart: always
    tty: true
    ports:
      - "2017:2017"
      - "10086:20172"
    environment:
      V2RAYA_V2RAY_BIN: /usr/local/bin/v2ray
# https://www.freeclashnode.com/uploads/2024/09/0-20240906.txt
# 需指定V2RAYA_V2RAY_BIN才能使用多路

  webdav:
  # 文件配置备份系统
    container_name: webdav
    hostname: webdav
    image: webdav
    restart: always
    tty: true
    ports:
      - "5005:80"
    volumes:
      - /home/webdav:/var/www/html
    command: "nginx -g 'daemon off;'"

  chronyd:
    container_name: chronyd
    hostname: chronyd.mm
    image: chronyd4.3
    restart: always
    tty: true
    ports:
      - "123:123/udp"
      - "323:323/udp"

  vlmcsd:
    container_name: vlmcsd
    hostname: vlmcsd.mm
    image: vlmcsd1113
    tty: true
    ports:
      - "1688:1688"

  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq.mm
    image: dnsmasq2.89
    tty: true
    volumes:
      - /etc/hosts:/etc/hosts
      - /logs/dnsmasq.log:/var/log/dnsmasq/dnsmasq.log
    ports:
      - "53:53/udp"

  dot:
    container_name: dot
    hostname: dot.mm
    image: dot
    tty: true
    ports:
      - "853:853/udp"
    command: "nginx -g 'daemon off;'"

  xunlei:
    container_name: xunlei
    hostname: xunlei.mm
    image: docker.io/cnk3x/xunlei
    user: root
    privileged: true
    tty: true
    volumes:
      - /home/nginx/xunlei/:/xunlei/downloads/
    environment:
      - XL_DASHBOARD_PORT=996
    ports:
      - "996:996"

  maomiav:
    container_name: maomiav
    hostname: maomiav.mm
    image: maomiav
    tty: true
    ports:
      - "213:213"

  socket5:
    container_name: socket5
    hostname: socket5.mm
    image: socket5
    tty: true
    ports:
      - "55555:55555"

  squid:
    container_name: squid5.7
    hostname: squid
    image: squid5.7
    tty: true
    ports:
      - "11111:3128"

  test:
    container_name: test
    hostname: test.mm
    image: debian12.x
    tty: true
    tmpfs: /tmpfs/
    volumes:
      - /home/nginx/temp/:/temp/
    working_dir: /temp
    ports:
      - "2222:22"
      - "9999:80"
# 默认进入temp目录操作: echo "cd /temp" >> .bashrc
