version: "2.2"

networks:
  macvlan:
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: enp8s0
    ipam:
      config:
        - subnet: 192.168.31.200/24
          ip_range: 192.168.31.200/28
          gateway: 192.168.31.1

services:
  java:
    container_name: java
    hostname: java.service
    image: java11.0
    tty: true
    mac_address: 20-00-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.200
    command: /usr/sbin/sshd -D

  databases:
    container_name: mariadb
    hostname: databases.service
    image: mariadb5.5
    tty: true
    mac_address: 20-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.201

  redis:
    container_name: redis
    hostname: redis.service
    image: redis3.2
    tty: true
    mac_address: 20-20-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.202

  seafile:
    container_name: seafile
    hostname: seafile.service
    image: seafile5.1
    tty: true
    mac_address: 02-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.210
    dns: 223.6.6.6
    command: >
      sh -c "/seafile/seafile-server-5.1.4/seafile.sh start &&
             /seafile/seafile-server-5.1.4/seahub.sh start 80 &&
             /usr/sbin/sshd -D"

  v2ray:
      container_name: v2ray
      hostname: v2ray.service
      image: v2ray4.45
      tty: true
      mac_address: 02-11-00-00-00-00
      networks:
        macvlan:
            ipv4_address: 192.168.31.211
      dns: 223.6.6.6
      command: sh -c "/update.sh && /v2ray run & /usr/sbin/sshd -D"

  v2ray-pc:
    container_name: v2ray-pc
    hostname: v2ray-pc.service
    image: v2ray4.45
    tty: true
    mac_address: 02-12-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.212
    dns: 223.6.6.6
    command: sh -c "/update.sh && /v2ray run & /usr/sbin/sshd -D"

  test:
    container_name: test
    hostname: test.service
    image: centos7.8
    tty: true
    mac_address: 02-22-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.222
    dns: 223.6.6.6
    command: /usr/sbin/sshd -D

  mail:
    container_name: mail
    hostname: mail.service
    image: mail
    tty: true
    mac_address: 02-05-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.205
    dns: 223.6.6.6
    command: sh -c "postfix start && dovecot && saslauthd -a pam && /usr/sbin/sshd -D"


  squid:
    container_name: squid
    hostname: squid.service
    image: squid
    tty: true
    mac_address: 02-06-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.31.206
    dns: 223.6.6.6
    command: sh -c "squid & /usr/sbin/sshd -D"
