version: "2.2"

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp8s0
    ipam:
      config:
        - subnet: 192.168.10.200/24
          ip_range: 192.168.10.200/28
          gateway: 192.168.10.1

services:
  java:
    container_name: java
    hostname: java.service
    image: java11.0
    tty: true
    mac_address: 20-00-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.200
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    command: /usr/sbin/sshd -D

  mariadb:
    container_name: mariadb
    hostname: mariadb.service
    image: mariadb5.5
    tty: true
    mac_address: 20-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.201
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
    - /home/data/mysql:/var/lib/mysql/
    command: /mariadb.sh

  redis:
    container_name: redis
    hostname: redis.service
    image: redis3.2
    tty: true
    mac_address: 20-20-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.202
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1

  seafile7:
    container_name: seafile7
    hostname: seafile7.service
    image: seafile7.0.5
    tty: true
    mac_address: 02-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.210
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /home/data/seafile/:/data/
    dns: 223.6.6.6
    command:  /seafile.sh

  v2ray:
      container_name: v2ray
      hostname: v2ray.service
      image: v2ray4.45
      tty: true
      mac_address: 02-11-00-00-00-00
      networks:
        macvlan:
            ipv4_address: 192.168.10.211
      sysctls:
        net.ipv6.conf.all.disable_ipv6: 1
      dns: 223.6.6.6
      command: sh -c "/update.sh & /v2ray run & /usr/sbin/sshd -D"

  xray:
    container_name: xray
    hostname: xray.service
    image: xray1.5
    tty: true
    mac_address: 02-12-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.212
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    dns: 223.6.6.6
    command: sh -c "/update.sh & /xray run -confdir=/ & /usr/sbin/sshd -D"

  test:
    container_name: test
    hostname: test.service
    image: centos7.8
    tty: true
    mac_address: 02-22-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.222
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    dns: 223.6.6.6
    command: /usr/sbin/sshd -D

  adb:
    container_name: adb
    hostname: adb.service
    image: adb
    tty: true
    mac_address: 02-08-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.208
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    dns: 192.168.10.1
    command: sh -c "/usr/sbin/sshd -D & /y5s.sh"

  mail:
    container_name: mail
    hostname: mail.service
    image: mail
    tty: true
    mac_address: 02-05-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.205
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    dns: 223.6.6.6
    command: sh -c "postfix start && dovecot && saslauthd -a pam && /usr/sbin/sshd -D"


  squid:
    container_name: squid
    hostname: squid.service
    image: squid
    tty: true
    mac_address: 02-06-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.206
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    dns: 223.6.6.6
    command: sh -c "squid & /usr/sbin/sshd -D"

  t219:
    container_name: t219
    hostname: test.service
    image: centos7.8
    tty: true
    mac_address: 02-19-00-00-00-00
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    networks:
      macvlan:
        ipv4_address: 192.168.10.219
    dns: 223.6.6.6
    command: /usr/sbin/sshd -D

  xunlei:
    container_name: xunlei
    hostname: xunlei.service
    image: cnk3x/xunlei:latest
    privileged: true
    tty: true
    mac_address: 02-09-00-00-00-00
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /home/nginx/x/:/xunlei/downloads/
      - /home/data/xunlei:/xunlei/data
    environment:
      - XL_WEB_PORT=80
    networks:
      macvlan:
        ipv4_address: 192.168.10.209

