server {
    listen 5005;
    listen 85;
    charset utf-8;
    autoindex on;
    root /var/www/webdav;
    #need to install libnginx-mod-http-dav-ext
    dav_methods PUT DELETE MKCOL COPY MOVE;
    dav_ext_methods PROPFIND OPTIONS;
    create_full_put_path  on;
    client_max_body_size 100000000m;
    #need password
    auth_basic "Please input password";
    auth_basic_user_file /passwd;
}