proxy_cache_path cache levels=1:2 keys_zone=sukebei:10m max_size=1g inactive=60m use_temp_path=off;
server {
    listen 83;

    location / {
        expires 30m;
        proxy_pass https://sukebei.moonchan.xyz;
        proxy_set_header Accept-Encoding "";
        proxy_hide_header Content-Encoding;
        # 启用缓存
        proxy_cache sukebei;
        proxy_cache_valid 200 30m; # 对 200 响应缓存 30 分钟
        proxy_cache_valid 404 5m; # 可选：对 404 缓存 5 分钟
        # 可选：添加缓存命中状态头（用于调试）
        add_header X-Cache-Status $upstream_cache_status;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }
}
