FROM scratch

ENV TZ='CST-8'
ADD  binaries.tar.gz /

CMD ["/binaries/Linux/intel/static/vlmcsd-x64-musl-static","-eD"]

# slmgr /skms 5.mm
# slmgr /ato
# https://github.com/Wind4/vlmcsd/releases/download/svn1113/binaries.tar.gz