version: "3.8"

services:
  nginx:
    container_name: zian
    hostname: zian.mm
    image: zian
    restart: always
    tty: true
    ports:
      - "80-88:80-88"
      - "5005:5005"
    volumes:
      - /home/nginx/:/home/nginx/
      - /home/webdav:/var/www/webdav
    working_dir: /home/nginx
    command: sh -c "nginx & goweb"

  quic:
    container_name: quic
    hostname: quic.mm
    image: nginx.quic
    restart: always
    tty: true
    ports:
      - "443:443/udp"
    command: sh -c "nginx & bash"

  chronyd:
    container_name: chronyd
    hostname: chronyd.mm
    image: chronyd4.3
    restart: always
    tty: true
    ports:
      - "123:123/udp"
      - "323:323/udp"

  vlmcsd:
    container_name: vlmcsd
    hostname: vlmcsd.mm
    image: vlmcsd1113
    tty: true
    ports:
      - "1688:1688"

  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq.mm
    image: dnsmasq2.89
    tty: true
    volumes:
      - /etc/hosts:/etc/hosts
    ports:
      - "53:53/udp"
