version: "3.8"
#https://docs.docker.com/compose/compose-file/compose-file-v3/
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      #parent: enp8s0
      parent: enp6s0
    ipam:
      config:
        - subnet: 10.0.0.100/24
          ip_range: 10.0.0.100/24
          gateway: 10.0.0.1

services:
  ffmpeg:
    container_name: ffmpeg
    hostname: 210.mm
    image: ffmpeg5.1
    tty: true
    tmpfs: /home/nginx/
    mac_address: 02-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.210
    command: sh -c "nginx & /usr/sbin/sshd -D"

  rtmp:
    container_name: rtmp
    hostname: 211.mm
    image: rtmp
    tty: true
    tmpfs: /tmp/
    mac_address: 02-15-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.215
    command: sh -c "/usr/local/nginx/sbin/nginx & /usr/sbin/sshd -D"

  flv:
    container_name: flv
    hostname: 212.mm
    image: flv
    tty: true
    tmpfs: /tmp/
    mac_address: 02-12-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.212
    command: sh -c "/usr/local/nginx/sbin/nginx & /usr/sbin/sshd -D"

  quic:
    container_name: quic
    hostname: quic.mm
    image: nginx.quic
    tty: true
    mac_address: 02-13-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.213
    command: sh -c "nginx & /usr/sbin/sshd -D"



  head:
    container_name: head
    hostname: 218.mm
    image:  mobz/elasticsearch-head:5-alpine
    tty: true
    mac_address: 02-18-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.218


  elasticsearch:
    container_name: elasticsearch
    hostname: 219.mm
    image:  elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
    tty: true
    mac_address: 02-19-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.219

  idea:
    container_name: idea
    hostname: 220.mm
    image: idea2024.1
    tty: true
    tmpfs: /tmpfs/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jetbrains/idea-IU-241.19072.14:/usr/idea/
      - /home/jetbrains/jetbra:/usr/jetbra/
      - /home/jetbrains/.m2:/root/.m2
    mac_address: 02-22-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.220

  test221:
    container_name: test221
    hostname: 221.mm
    image: debian12.x
    tty: true
    mac_address: 02-21-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.221
#    command:  sh -c "nginx ; /usr/sbin/sshd -D"

  test222:
    container_name: test222
    hostname: 222.mm
    image: hadoop3.4.1
    tty: true
    mac_address: 02-22-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 10.0.0.222