version: "3.8"

services:
  nginx:
    container_name: nginx
    hostname: nginx.mm
    image: nginx1.22
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - /home/nginx/:/home/nginx/
    command: sh -c "nginx & /var/www/html/.go"

  chronyd:
    container_name: chronyd
    hostname: chronyd.mm
    image: chronyd4.3
    restart: always
    tty: true
    ports:
      - "123:123/udp"
      - "323:323/udp"

  vlmcsd:
    container_name: vlmcsd
    hostname: vlmcsd.mm
    image: vlmcsd1113
    tty: true
    ports:
      - "1688:1688"

  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq.mm
    image: dnsmasq2.89
    tty: true
    volumes:
      - /etc/hosts:/etc/hosts
    ports:
      - "53:53/udp"
