version: "3.8"
#https://docs.docker.com/compose/compose-file/compose-file-v3/
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp8s0
    ipam:
      config:
        - subnet: 192.168.10.200/24
          ip_range: 192.168.10.200/28
          gateway: 192.168.10.1

services:
  nginx:
    container_name: nginx
    hostname: nginx.mm
    image: nginx1.22
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - /home/nginx/:/home/nginx/
    command: sh -c "nginx & /var/www/html/.go"

  java:
    container_name: java
    hostname: java.service
    image: java17.0
    tty: true
    mac_address: 02-00-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.200
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /home/java:/java
    command: /usr/sbin/sshd -D

  graalvm:
    container_name: graalvm
    hostname: graalvm.service
    image: graalvm17.0
    tty: true
    mac_address: 02-01-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.201
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /home/java:/java
    command: /usr/sbin/sshd -D

  redis:
    container_name: redis
    hostname: 202.mm
    image: redis7.0
    tty: true
    mac_address: 02-02-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.202
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /home/redis:/var/lib/redis/
    command: sh -c "/usr/bin/redis-server /etc/redis/redis.conf & /usr/sbin/sshd -D"

  ipv6:
    container_name: ipv6
    hostname: 206.mm
    image: ipv6
    tty: true
    mac_address: 02-06-00-00-00-00
    networks:
      default:
        ipv4_address: 172.18.0.6
      macvlan:
        ipv4_address: 192.168.10.206
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - /home/nginx/:/home/nginx/ #仅用作于ssh操作
    command: sh -c "nginx & /usr/sbin/sshd -D"

  gitlab:
    container_name: gitlab
    hostname: 207.mm
    image: gitlab/gitlab-ce
    tty: true
    mac_address: 02-07-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.207

  adb:
    container_name: adb
    hostname: 208.mm
    image: adb34.0
    tty: true
    mac_address: 02-08-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.208
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    command: /usr/sbin/sshd -D

  xunlei:
    container_name: xunlei
    hostname: 209.mm
    image: docker.io/cnk3x/xunlei
    user: root
    privileged: true
    tty: true
    mac_address: 02-09-00-00-00-00
    volumes:
      - /home/nginx/xunlei/:/xunlei/downloads/
    environment:
      - XL_WEB_PORT=80
    dns: 223.6.6.6
    networks:
      macvlan:
        ipv4_address: 192.168.10.209

  jenkins:
    container_name: jenkins
    hostname: 210.mm
    image: jenkins2.414
    tty: true
    tmpfs: /tmpfs/
    mac_address: 02-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.210
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    command: sh -c "/usr/sbin/sshd -D & jenkins"

  terminal:
    container_name: terminal
    hostname: 217.mm
    image: terminal
    tty: true
    environment:
      GUACD_HOSTNAME: terminal
      SERVER_ADDR : 0.0.0.0:80
    volumes:
      - /home/terminal/:/usr/local/next-terminal/data
    mac_address: 02-17-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.217