version: "3.8"
#https://docs.docker.com/compose/compose-file/compose-file-v3/
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp8s0
    ipam:
      config:
        - subnet: 192.168.10.200/24
          ip_range: 192.168.10.200/28
          gateway: 192.168.10.1

services:
  java:
    container_name: java
    hostname: java.service
    image: java17.0
    tty: true
    mac_address: 02-00-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.200
    volumes:
      - /home/java:/java

  graalvm:
    container_name: graalvm
    hostname: graalvm.service
    image: graalvm17.0
    tty: true
    mac_address: 02-01-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.201
    volumes:
      - /home/java:/java

  redis:
    container_name: redis
    hostname: 202.mm
    image: redis7.0
    tty: true
    mac_address: 02-02-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.202
    volumes:
      - /home/redis:/var/lib/redis/


  mariadb:
    container_name: mariadb
    hostname: 203.mm
    image: mariadb10.11
    tty: true
    mac_address: 02-03-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.203
    volumes:
      - /home/mariadb/:/var/lib/mysql

  ipv6:
    container_name: ipv6
    hostname: 206.mm
    image: ipv6
    tty: true
    mac_address: 02-06-00-00-00-00
    networks:
      default:
        ipv4_address: 172.18.0.6
      macvlan:
        ipv4_address: 192.168.10.206
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - /home/nginx/:/home/nginx/

  gitlab:
    container_name: gitlab
    hostname: 207.mm
    image: gitlab/gitlab-ce
    tty: true
    mac_address: 02-07-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.207

  adb:
    container_name: adb
    hostname: 208.mm
    image: adb34.0
    tty: true
    mac_address: 02-08-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.208

  xunlei:
    container_name: xunlei
    hostname: 209.mm
    image: docker.io/cnk3x/xunlei
    user: root
    privileged: true
    tty: true
    mac_address: 02-09-00-00-00-00
    volumes:
      - /home/nginx/xunlei/:/xunlei/downloads/
    environment:
      - XL_WEB_PORT=80
    dns: 223.6.6.6
    networks:
      macvlan:
        ipv4_address: 192.168.10.209

  jenkins:
    container_name: jenkins
    hostname: 210.mm
    image: jenkins2.414
    tty: true
    mac_address: 02-10-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.210

  maomiav1:
    container_name: maomiav1
    hostname: maomiav1.mm
    image: maomiav1
    tty: true
    mac_address: 02-11-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.211

  maomiav2:
    container_name: maomiav2
    hostname: maomiav2.mm
    image: maomiav2
    tty: true
    mac_address: 02-12-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.212

  terminal:
    container_name: terminal
    hostname: 217.mm
    image: terminal1.5
    tty: true
    environment:
      GUACD_HOSTNAME: terminal
      SERVER_ADDR : 0.0.0.0:80
    volumes:
      - /home/terminal/:/usr/local/next-terminal/data
    mac_address: 02-17-00-00-00-00
    networks:
      macvlan:
        ipv4_address: 192.168.10.217