map $arg_from $custom_index {
    default       "index.html";
    "/m3u8/"      "m3u8.html";
    "/note/"      "note.html";
}

server {
listen 80;
charset 'utf-8';
root /var/www/autoindex;
client_max_body_size 8192m;
add_header Access-Control-Allow-Origin *;
#location /su {proxy_pass https://suggestion.baidu.com/su;}
location /json/{autoindex on;autoindex_format json;alias /home/nginx/;}
location /8888/ {proxy_pass http://127.0.0.1:8888/;}
location / {index $custom_index;}
location = /get {default_type text/plain;
return 200 "Addr: $remote_addr\nX-real-ip: $http_x_real_ip\nX-forwarded-for: $http_x_forwarded_for
User-Agent: $http_user_agent\nAccept: $http_accept\nReferer: $http_referer\nAccept-Language: $http_accept_language";}
}